# -*- coding: utf-8 -*-
"""Summer_Olympics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qB2gZpL_Q2Vz06eo93oei6RtViKZOiV6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("summer.csv")

df

df.head()

"""# 1. In how many cities Summer Olympics is held so far?"""

Total_cities = len(df['City'].unique())

Total_cities

"""#2. Which sport is having most number of Gold Medals so far? (Top 5)

"""

data = []
gold_medal = df[df['Medal']=='Gold']
for sport in gold_medal['Sport'].unique():
  data.append([sport, len(gold_medal[gold_medal['Sport']==sport])])
data = pd.DataFrame(data, columns=['Sport', 'Gold']).sort_values(by='Gold', ascending=False).head()
data.plot(x='Sport', y='Gold', kind='bar', figsize=(10, 5))

"""#3. Which sport is having most number of medals so far? (Top 5)"""

df

df.groupby('Sport').count()['Medal'].sort_values(ascending=False).head().plot.bar(figsize=(10, 5))

"""#4. Which player has won most number of medals? (Top 5)¶"""

df.groupby('Athlete').count()['Medal'].sort_values(ascending = False).head().plot.bar(figsize=(10,5))



"""#5. Which player has won most number Gold Medals of medals? (Top 5)"""



gold_medal.groupby('Athlete').count()['Medal'].sort_values(ascending = False).head().plot.bar(figsize=(10,5))

"""#6. In which year India won first Gold Medal in Summer Olympics?¶"""

first_medal = gold_medal[gold_medal['Country'] == 'IND']['Year'].min()

first_medal

"""#7. Which event is most popular in terms on number of players? (Top 5)"""

popular_event = df.groupby("Event").count()['Athlete'].sort_values(ascending=False).head().plot.bar(figsize=(10, 5))



"""#8. Which sport is having most female Gold Medalists? (Top 5)"""

data =[]
gold_female = gold_medal[gold_medal['Gender'] == 'Women']
for sport in gold_female['Sport'].unique():
  data.append([sport, len(gold_female[gold_female['Sport']==sport])])
data= pd.DataFrame(data, columns=['Sport', 'GoldFemale']).sort_values(by='GoldFemale', ascending=False).head()
data.plot(x='Sport' ,y='GoldFemale', kind='bar', figsize=(5, 5))